Repository MicrosoftDocs/visualstudio-docs.ja-jp, pull requests merged in 2018-12, with the labels that each got.

#106 change to natural japanese
  docs/modeling/code-generation-in-a-build-process.md
Labels: Accepted, Linguistic Suggestion

#107 Update text-template-control-blocks.md
  docs/modeling/text-template-control-blocks.md
Labels: Accepted, Linguistic Suggestion

#108 Update text-template-utility-methods.md
  docs/modeling/text-template-utility-methods.md
Labels: Accepted, Linguistic Suggestion

#110 Update accessing-visual-studio-or-other-hosts-from-a-text-template.md
  docs/modeling/accessing-visual-studio-or-other-hosts-from-a-text-template.md
Labels: Accepted, Linguistic Suggestion

#111 Update using-escape-sequences-in-text-templates.md
  docs/modeling/using-escape-sequences-in-text-templates.md
Labels: Accepted, Linguistic Suggestion

#112 Update how-to-generate-templates-from-templates-by-using-escape-seque…
  docs/modeling/how-to-generate-templates-from-templates-by-using-escape-sequences.md
Labels: Accepted, Linguistic Suggestion

#117 Typo
  docs/ide/how-to-specify-build-events-visual-basic.md
Labels: Accepted, Linguistic Suggestion

#116 Typo
  docs/designers/designing-xaml-in-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#115 Update debugging-a-t4-text-template.md
  docs/modeling/debugging-a-t4-text-template.md
Labels: Accepted, Linguistic Suggestion

#120 Update
  docs/extensibility/installing-the-visual-studio-sdk.md
Labels: Accepted, Linguistic Suggestion

#128 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/regular-expression-object-expected.md
Labels: Accepted, Linguistic Suggestion

#131 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/date-object-expected.md
Labels: Accepted, Linguistic Suggestion

#132 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/can-t-have-continue-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#133 ために ループ → for ループに訳し直した。
  scripting-docs/javascript/misc/can-t-have-continue-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#134 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-colon.md
Labels: Accepted, Linguistic Suggestion

#135 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-at-end.md
Labels: Accepted, Linguistic Suggestion

#138 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-equal-javascript.md
Labels: Accepted, Linguistic Suggestion

#139 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-minus.md
Labels: Accepted, Linguistic Suggestion

#140 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-right-square-bracket.md
Labels: Accepted, Linguistic Suggestion

#141 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-while.md
Labels: Accepted, Linguistic Suggestion

#142 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-at.md
Labels: Accepted, Linguistic Suggestion

#143 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-left-parenthesis-javascript.md
Labels: Accepted, Linguistic Suggestion

#144 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-var.md
Labels: Accepted, Linguistic Suggestion

#145 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/with-not-available-in-the-ecma-327-compact-profile.md
Labels: Accepted, Linguistic Suggestion

#148 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-right-parenthesis-javascript.md
Labels: Accepted, Linguistic Suggestion

#151 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/can-t-have-break-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#152 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/return-statement-outside-of-function.md
Labels: Accepted, Linguistic Suggestion

#150 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-right-square-bracket-in-regular-expression-javascript.md
Labels: Accepted, Linguistic Suggestion

#149 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-right-parenthesis-in-regular-expression-javascript.md
Labels: Accepted, Linguistic Suggestion

#127 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-catch.md
Labels: Accepted, Linguistic Suggestion

#129 左側のタイトルと合わせため、訳し直しました。
  scripting-docs/javascript/misc/expected-right-curly-brace.md
Labels: Accepted, Linguistic Suggestion

#156 この → 'this' (JavaScript keyword)
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion

#158 この → 'this' (JavaScript keyword)
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion

#160 これ → 'this' (JavaScript keyword)
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion

#157 新しい → 'new' (JavaScript keyword)
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion

#154 これ → 'this' (JavaScript keyword)
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion

#121 Update
  docs/extensibility/extensibility-hello-world.md
Labels: Accepted

#153 セッター関数 → Setter 関数 に統一
  scripting-docs/javascript/misc/setter-functions-must-have-one-argument.md
Labels: In Progress, Linguistic Suggestion
