Repository MicrosoftDocs/visualstudio-docs.ja-jp, pull requests merged in 2018-06, with the labels that each got.

#32 Update assembly-element-clickonce-deployment.md
  docs/deployment/assembly-element-clickonce-deployment.md
Labels: Accepted, Linguistic Suggestion

#33 Update assemblyidentity-element-clickonce-application.md
  docs/deployment/assemblyidentity-element-clickonce-application.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#36 Update deployment-element-clickonce-deployment.md
  docs/deployment/deployment-element-clickonce-deployment.md
Labels: In Progress, Linguistic Suggestion

#40 change フットプリント to 占有領域
  docs/install/change-installation-locations.md
Labels: Accepted, Linguistic Suggestion

#41 Update deploying-applications-services-and-components.md
  docs/deployment/deploying-applications-services-and-components.md
Labels: Accepted, Linguistic Suggestion

#43 Update quickstart-deploy-to-local-folder.md
  docs/deployment/quickstart-deploy-to-local-folder.md
Labels: Accepted, Linguistic Suggestion

#44 Update starting-to-develop-visual-studio-extensions.md
  docs/extensibility/starting-to-develop-visual-studio-extensions.md
Labels: Accepted, Linguistic Suggestion
