Repository MicrosoftDocs/visualstudio-docs.ja-jp, pull requests merged in 2019-08, with the labels that each got.

#1815 fix "プル要求"→"プルリクエスト"
  docs/ide/reference/team-explorer-reference.md
Labels: Linguistic Suggestion, Partially Accepted

#1817 fix "C と C++ コードの欠陥を削減する SAL 注釈を使って"→"SAL 注釈を使って C/C++ のコード障害を減らす方法"
  docs/code-quality/c6525.md
Labels: Accepted, Linguistic Suggestion

#1819 empty → 空の
  docs/get-started/tutorial-projects-solutions.md
Labels: Accepted

#1822 [新しいプロジェクト] → [新しい項目]
  docs/get-started/tutorial-projects-solutions.md
Labels: Accepted, Linguistic Suggestion

#1824 unit test → 単体テスト
  docs/get-started/tutorial-projects-solutions.md
Labels: Accepted, Linguistic Suggestion

#1826 [LOC] Back-Translation "お試しくださいブロック"→"try ブロック"
  scripting-docs/javascript/misc/exception-thrown-and-not-caught.md
Labels: Accepted

#1827 Windows → ウィンドウ
  docs/get-started/tutorial-projects-solutions.md
Labels: Accepted, Linguistic Suggestion

#1829 分かち書きをしていない為にイタリック指定が正しく効いてない箇所の修正
  docs/install/create-an-offline-installation-of-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#1833 タイトルから 2017 を除去
  docs/install/modify-visual-studio.md
Labels: Accepted

#1832 タイトルから 2017 を除去
  docs/install/update-visual-studio.md
Labels: Accepted

#1834 タイトルから 2017 を除去
  docs/toc.yml
Labels: Accepted
