Repository MicrosoftDocs/visualstudio-docs.ja-jp, pull requests merged in 2019-03, with the labels that each got.

#1713 Fix missing
  docs/debugger/a-dcom-error-occurred-trying-to-contact-the-remote-computer-access-is-denied.md
Labels: Accepted, Linguistic Suggestion

#1716 Fix missing
  docs/debugger/assertions-in-managed-code.md
Labels: Accepted, Linguistic Suggestion

#1717 Fix missing
  docs/debugger/choose-breakpoints-dialog-box.md
Labels: Accepted, Linguistic Suggestion

#1718 Fix missing
  docs/debugger/client-block-hook-functions.md
Labels: Accepted, Linguistic Suggestion

#1720 Fix missing
  docs/debugger/com-and-activex-debugging.md
Labels: Accepted, Linguistic Suggestion

#1719 Fix missing
  docs/debugger/client-side-script-debugging.md
Labels: Accepted, Linguistic Suggestion

#1721 Fix missing
  docs/debugger/configure-firewall-for-remote-debugging-dialog-box.md
Labels: Accepted, Linguistic Suggestion

#1714 Fix missing
  docs/debugger/allocation-hook-functions.md
Labels: Accepted, Linguistic Suggestion

#1715 Fix missing
  docs/debugger/aspnet-debugging-system-requirements.md
Labels: Accepted, Linguistic Suggestion

#1722 Fix missing
  docs/debugger/create-custom-views-of-dot-managed-objects.md
Labels: Accepted, Linguistic Suggestion

#1726 Fix missing
  docs/debugger/debug-a-webview-control.md
Labels: Accepted, Linguistic Suggestion

#1729 Fix missing
  docs/debugger/debugbreak-and-debugbreak.md
Labels: Accepted, Linguistic Suggestion

#1731 Fix missing
  docs/debugger/debugger-security.md
Labels: Accepted, Linguistic Suggestion

#1732 Fix missing
  docs/debugger/debugger-settings-and-preparation.md
Labels: Accepted, Linguistic Suggestion

#1728 Fix missing
  docs/debugger/debug-threads-and-processes.md
Labels: Accepted, Linguistic Suggestion

#1723 Fix missing
  docs/debugger/crt-debug-library-use.md
Labels: Accepted, Linguistic Suggestion

#1733 Fix missing
  docs/vs-2015/profiling/nameprofile.md
Labels: Accepted, Linguistic Suggestion

#1734 Fix missing
  scripting-docs/winscript/windows-script-engines.md
Labels: Accepted, Linguistic Suggestion

#1735 Fix typo
  docs/cross-platform/application-lifecycle-management-alm-with-unity-apps.md
Labels: Accepted, Linguistic Suggestion

#1736 Fix typo
  docs/vs-2015/cross-platform/application-lifecycle-management-alm-with-unity-apps.md
Labels: Accepted, Linguistic Suggestion

#1737 Fix typo
  docs/vs-2015/cross-platform/application-lifecycle-management-alm-with-xamarin-apps.md
Labels: Accepted, Linguistic Suggestion

#1738 Fix typo
  docs/vs-2015/misc/analyze-dotnet-framework-memory-issues.md
Labels: Accepted, Linguistic Suggestion

#1739 Delete unnecessary brackets
  docs/extensibility/internals/list-of-available-services.md
Labels: Accepted, Linguistic Suggestion

#1740 Improve translation
  docs/extensibility/adding-an-lsp-extension.md
Labels: Linguistic Suggestion, Partially Accepted

#1748 Visual c# → Visual C#
  docs/vsto/walkthrough-calling-code-from-vba-in-a-visual-csharp-project.md
Labels: Accepted, Linguistic Suggestion

#1750 Visual c# → Visual C#
  docs/vsto/project-solutions.md
Labels: Accepted, Linguistic Suggestion

#1749 Visual c# → Visual c#
  docs/vsto/update-ribbon-customizations-in-office-projects-to-migrate-to-dotnet-framework-4-or-4-5.md
Labels: Accepted, Linguistic Suggestion

#1747 Visual c# → Visual C#
  docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md
Labels: Accepted, Linguistic Suggestion

#1758 します。NETFramework → .NETFramework
  docs/vsto/how-to-configure-inclusion-list-security.md
Labels: Accepted

#1754 Visual c# → Visual C#
  docs/vsto/how-to-programmatically-use-built-in-dialog-boxes-in-word.md
Labels: Accepted

#1752 Visual c# → Visual C#
  docs/vsto/late-binding-in-office-solutions.md
Labels: Accepted

#1751 Visual c# → Visual C#
  docs/vsto/optional-parameters-in-office-solutions.md
Labels: Accepted

#1756 Visual c# → Visual C#
  docs/vsto/how-to-expose-code-to-vba-in-a-visual-basic-project.md
Labels: Accepted

#1755 Visual c# → Visual C#
  docs/vsto/how-to-expose-code-to-vba-in-a-visual-csharp-project.md
Labels: Accepted

#1757 Visual c# → Visual C#
  docs/vsto/how-to-configure-inclusion-list-security.md
Labels: Accepted

#1753 Visual c# → Visual C#
  docs/vsto/how-to-programmatically-use-word-dialog-boxes-in-hidden-mode.md
Labels: Accepted

#1585 Fix missing
  docs/vs-2015/extensibility/internals/rdt-readlock-usage.md
Labels: Accepted, Technical Issue

#1769 Visual c# → Visual C#
  docs/modeling/map-dependencies-across-your-solutions.md
Labels: In Progress, Linguistic Suggestion

#1768 Visual c# → Visual C#
  docs/sharepoint/creating-item-templates-and-project-templates-for-sharepoint-project-items.md
Labels: Accepted, Linguistic Suggestion

#1771 Update msbuild-reserved-and-well-known-properties.md
  docs/msbuild/msbuild-reserved-and-well-known-properties.md
Labels: Accepted, In Progress

#1772 Visual c# → Visual C#
  docs/modeling/layer-diagrams-guidelines.md
Labels: Accepted, In Progress

#1759 Visual c# → Visual C#
  docs/vsto/combining-vba-and-document-level-customizations.md
Labels: Linguistic Suggestion, Partially Accepted

#1760 Visual c# → Visual C#
  docs/vsto/collaborative-development-of-office-solutions.md
Labels: Accepted, Linguistic Suggestion

#1761 (など\ \ Servername\Sharename) → (\ \ Servername\Sharename など)
  docs/vsto/collaborative-development-of-office-solutions.md
Labels: Linguistic Suggestion, Partially Accepted

#1762 Visual c# → Visual C#
  docs/sharepoint/walkthrough-creating-a-site-column-project-item-with-a-project-template-part-2.md
Labels: Linguistic Suggestion, Partially Accepted

#1763 Visual c# → Visual C#
  docs/sharepoint/walkthrough-creating-a-silverlight-web-part-that-displays-odata-for-sharepoint.md
Labels: Linguistic Suggestion, Partially Accepted

#1764 Visual c# → Visual C#
  docs/sharepoint/walkthrough-creating-a-custom-action-project-item-with-an-item-template-part-2.md
Labels: Linguistic Suggestion, Partially Accepted

#1767 A .vstemplateファイル。 → .vstemplateファイル
  docs/sharepoint/creating-item-templates-and-project-templates-for-sharepoint-project-items.md
Labels: Accepted, Linguistic Suggestion
