Repository MicrosoftDocs/visualstudio-docs.ja-jp, pull requests merged in 2020-01, with the labels that each got.

#1894 [LOC]Fixed inappropriate japanese "[ステートメントで]"→"[with ステートメント]"
  scripting-docs/javascript/misc/with-not-available-in-the-ecma-327-compact-profile.md
Labels: Accepted, Linguistic Suggestion

#1873 [LOC] Back-Translation "[関数オブジェクト]"→"[Function オブジェクト]"
  scripting-docs/javascript/misc/cannot-assign-to-a-function-result.md
Labels: Accepted, Linguistic Suggestion

#1875 [LOC]Erasure "@ No__t-0"
  scripting-docs/javascript/misc/syntax-error-javascript.md
Labels: Accepted, Linguistic Suggestion

#1877 [LOC] Back-Translation "番号"→"Number"
  scripting-docs/javascript/misc/the-number-of-fractional-digits-is-out-of-range.md
Labels: Accepted, Linguistic Suggestion

#1878 [LOC]Back-Translation "[データ オブジェクト]"→"[Date オブジェクト]"
  scripting-docs/javascript/misc/date-object-expected.md
Labels: Accepted, Linguistic Suggestion

#1879 [LOC]Back-Translation "ために ループ "→"for ループ"
  scripting-docs/javascript/misc/can-t-have-continue-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#1884 [LOC]Back-Translation "**新しい**演算子"→"**new**演算子"
  scripting-docs/javascript/misc/cannot-assign-to-this.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#1885 [LOC] Back-Translation "[関数オブジェクト]"→"[Function オブジェクト]"
  scripting-docs/javascript/misc/function-does-not-have-a-valid-prototype-object.md
Labels: Accepted, Linguistic Suggestion

#1898 Update msbuild-conditions.md
  docs/msbuild/msbuild-conditions.md
Labels: Accepted

#1892 [LOC]Back-Translation "文字列"→"String"
  scripting-docs/javascript/misc/string-expected.md
Labels: Accepted, Linguistic Suggestion

#1896 [LOC]Fixed inappropriate japanese "値と参照渡しの引数を渡す"→"引数の値渡しと参照渡し"
  docs/vsto/optional-parameters-in-office-solutions.md
Labels: Accepted, Linguistic Suggestion

#1900 Typo
  docs/javascript/create-application-with-vuejs.md
Labels: Accepted

#1903 Typo " [EncodeURI 関数]"→" [encodeURI 関数]"
  scripting-docs/javascript/misc/the-uri-to-be-encoded-contains-an-invalid-character.md
Labels: Accepted, Linguistic Suggestion

#1902 [LOC]Fixed inappropriate japanese "**Instanceof**を使用して"→"**Instanceof…
  scripting-docs/javascript/misc/function-does-not-have-a-valid-prototype-object.md
Labels: Accepted, Linguistic Suggestion

#1904 [LOC]Back-Translation "**プロトタイプ**"→"**Boolean.prototype.toString**"
  scripting-docs/javascript/misc/boolean-expected.md
Labels: Accepted, Linguistic Suggestion

#1911 [LOC]Back-Translation "[関数オブジェクト]"→"[Function オブジェクト]"
  scripting-docs/javascript/misc/return-statement-outside-of-function.md
Labels: Accepted, Linguistic Suggestion

#1912 Typo "[Switch ステートメント]"→" [switch ステートメント]"
  scripting-docs/javascript/misc/default-can-only-appear-once-in-a-switch-statement.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#1913 Typo "[DecodeURI 関数]"→" [decodeURI 関数]"
  scripting-docs/javascript/misc/the-uri-to-be-decoded-is-not-a-valid-encoding.md
Labels: Accepted

#1915 [LOC]Erasure "の"
  scripting-docs/javascript/misc/expected-equal-javascript.md
Labels: Accepted, Linguistic Suggestion

#1914 [LOC]Fixed inappropriate japanese "次を参照してください。"
  scripting-docs/javascript/misc/expected-var.md
Labels: Accepted, Linguistic Suggestion

#1905 [LOC] Back-Translation "**ラベル**"→"**label**"
  scripting-docs/javascript/misc/can-t-have-break-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#1906 [LOC]Fixed inappropriate japanese "' Continue ' をループの外側に設定することはできません"…
  scripting-docs/javascript/misc/can-t-have-continue-outside-of-loop.md
Labels: Accepted, Linguistic Suggestion

#1907 [LOC]Fixed inappropriate japanese "16進数字 | が必要です。"→"16 進数の数字が必要です。"
  scripting-docs/javascript/misc/expected-hexadecimal-digit.md
Labels: Accepted, Linguistic Suggestion

#1908 Typo 'While'→'while'
  scripting-docs/javascript/misc/expected-while.md
Labels: Linguistic Suggestion, Partially Accepted, Technical Issue

#1910 [LOC]Fixed inappropriate japanese "未終了のコメント"→"未終了のコメントです。"
  scripting-docs/javascript/misc/unterminated-comment.md
Labels: Accepted, Linguistic Suggestion
